image:
    - Visual Studio 2022
    - Visual Studio 2019    
    - Visual Studio 2017

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\commsdsl
shallow_clone: true             

platform:
    - x86
    - x64

configuration:
    - Debug
    - Release

environment:
    COMMS_BRANCH: master
    CC_TOOLS_QT_BRANCH: master
    matrix:
        - CPP_STD: 11
        - CPP_STD: 14
        - CPP_STD: 17
        - CPP_STD: 20

matrix:
    fast_finish: false
    exclude:
        - image: Visual Studio 2017
          CPP_STD: 20                           
        
install:
    - call script\appveyor_install.bat
    - set PATH=%PATH%;%QTDIR%\bin
    - set BUILD_DIR=%APPVEYOR_BUILD_FOLDER%\build.%PLATFORM%.%CONFIGURATION%.%TOOLCHAIN%
    - if exist %BUILD_DIR% rmdir /S /Q %BUILD_DIR%
    - set COMMS_TAG=%COMMS_BRANCH%
    - set CC_TOOLS_QT_TAG=%CC_TOOLS_QT_BRANCH%
    - set COMMON_INSTALL_DIR=%BUILD_DIR%\install
    - set COMMON_BUILD_TYPE=%CONFIGURATION%
    - set COMMON_CXX_STANDARD=%CPP_STD%
    - call script\prepare_externals.bat

build_script:
    - echo ------------------------- Building Project -------------------------
    - cd %BUILD_DIR%
    - cmake .. -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G "NMake Makefiles" -DCMAKE_INSTALL_PREFIX="%COMMON_INSTALL_DIR%" ^
        -DCMAKE_PREFIX_PATH="%COMMON_INSTALL_DIR%" -DCOMMSDSL_TESTS_CXX_STANDARD=%CPP_STD% ^
        -DCOMMSDSL_BUILD_UNIT_TESTS=ON -DCOMMSDSL_BUILD_COMMSDSL2TEST=ON -DCOMMSDSL_BUILD_COMMSDSL2TOOLS_QT=ON
    - cmake --build . --config %CONFIGURATION% --target install
    - echo ------------------------- Testing -------------------------
    - ctest



