image:
    - Visual Studio 2022
    - Visual Studio 2019    
    - Visual Studio 2017

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\commsdsl
shallow_clone: true             

platform:
    - x86
    - x64

configuration:
    - Debug
    - Release

environment:
    matrix:
        - CPP_STD: 11
        - CPP_STD: 14
        - CPP_STD: 17
        - CPP_STD: 20

matrix:
    fast_finish: false
    exclude:
        - image: Visual Studio 2017
          CPP_STD: 20                           
        
install:
    - call script\appveyor_install.bat
    - set PATH=%PATH%;%QTDIR%\bin

build_script:
    - set BUILD_DIR=%APPVEYOR_BUILD_FOLDER%\build.%PLATFORM%.%CONFIGURATION%.%TOOLCHAIN%
    - if exist %BUILD_DIR% rmdir /S /Q %BUILD_DIR%
    - mkdir %BUILD_DIR%
    - cd %BUILD_DIR%
    - cmake .. -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G "NMake Makefiles" 
        -DCOMMSDSL_QT_DIR=%QTDIR% -DCOMMSDSL_TESTS_CXX_STANDARD=%CPP_STD% 
        -DCOMMSDSL_BUILD_UNIT_TESTS=ON        
    - set PATH=%BUILD_DIR%\lib\src;%PATH%
    - echo Building in %BUILD_DIR%
    - echo PATH = %PATH%
    - nmake

test_script:
    - ctest 



